---
version: "2"

# Need do configure 'Test coverage' under 'Analysis'? 

checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.

plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  markdownlint:
    enabled: true
    config:
      code_blocks: false
      tables: false
  shellcheck:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - FIXME
        - BUG
        - NOTE

exclude_patterns:
  - .vendor/
  - benchmarks/**/*

# vim: set ts=2 sw=2 et:
