---
output:
  # print lines of code with issue, default is true
  print-issued-lines: false

# all available settings of specific linters
linters-settings:
  govet:
    enable-all: true
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/davecgh/go-spew/spew"
            desc: "only used for debugging"
          - pkg: "github.com/c2fo/testify"
            desc: "wrong testify package"
  misspell:
    locale: US
  gocritic:
    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint run`
    # to see all tags and checks. Empty list by default. See
    # https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
  wsl:
    # Force newlines in end of case at this limit (0 = never).
    force-case-trailing-whitespace: 0

linters:
  enable-all: true
  disable:
    - cyclop
    - copyloopvar
    - dupl
    - execinquery
    - exhaustruct
    - forbidigo
    - funlen
    - gci
    - gocognit
    - gocyclo
    - godox
    - gomnd
    - lll
    - mnd
    - nakedret
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - testpackage
  disable-all: false
  fast: false

issues:
  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: true

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is
  # 3.
  max-same-issues: 0
# vim: set sw=2 ts=2 et:
