---
# all available settings of specific linters
linters-settings:
  stylecheck:
    # STxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    checks: ["all", "-ST1000"]
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/davecgh/go-spew/spew"
            desc: "only used for debugging"
          - pkg: "github.com/c2fo/testify"
            desc: "wrong testify package"
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - depguard
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - gci
    - gocritic
    - godox
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - predeclared
    - reassign
    - sloglint
    - staticcheck
    - stylecheck
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl
issues:
  exclude-use-default: false
  exclude-rules:
    - path: '(testing.go)|((.+)_test\.go)'
      linters:
        - errcheck
        - gosec
    - text: "Error return value of `.*\\.Close` is not checked"
      linters:
        - errcheck
    - text: G104
      linters:
        - gosec
# vim: set sw=2 ts=2 et:
    #
