language: go
go:
  - "1.10"

install:
  - go get -v github.com/golang/dep/cmd/dep
  - go get -v github.com/codeclimate/test-reporter
  - dep ensure -v -vendor-only

env:
 - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

before_script:
  - test-reporter before-build

script: 
  - go test -v -coverprofile c.out ./...

after_script:
  - test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    on_success: change
    on_failure: change

# vim: set ts=2 sw=2 et:
