language: go
go:
  - "1.12"

services:
  - rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
env:
  global:
    - CC_TEST_REPORTER_ID=7d839e0bef19ceb83a38550bc5e651070cd1c15279069a90bdbaaad727d7c0cd
    - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/
    - GO111MODULE=on

before_script:
  - sudo rabbitmq-plugins enable rabbitmq_management
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test -race -v -coverprofile c.out ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    on_success: change
    on_failure: change

# vim: set ts=2 sw=2 et:
