---
name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  AMQP_URL: amqp://guest:guest@127.0.0.1:45672
  CC_TEST_REPORTER_ID: 7d839e0bef19ceb83a38550bc5e651070cd1c15279069a90bdbaaad727d7c0cd

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27
  run-tests:
    needs: golangci-lint # run after golangci-lint action to not produce duplicated errors
    strategy:
      matrix:
        go:
          - 1.13
          - 1.14
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Test code
        run: go test -race -v ./...
  coverage:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download cc-test-reporter
        run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - name: Make cc-test-reporter executable
        run: chmod +x ./cc-test-reporter
      - name: run cc-test-reporter before-build
        run: ./cc-test-reporter before-build
      - name: Test and publish code coverage
        run: go test -coverprofile c.out ./...
      - name: Publish test results
        run: ./cc-test-reporter after-build --exit-code $?
