---
name: CI
on:
  push:
    branches:
      - master
  pull_request:


env:
  AMQP_URL: amqp://guest:guest@127.0.0.1:45672

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27
  run-tests:
    needs: golangci-lint # run after golangci-lint action to not produce duplicated errors
    strategy:
      matrix:
        go:
          - 1.13
          - 1.14
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start RabbitMQ server
        uses: getong/rabbitmq-action@v1.2
        with:
          rabbitmq version: '3.8.2-management-alpine'
          host port: 45672
          rabbitmq user: 'guest'
          rabbitmq password: 'guest'
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Test code
        run: go test -race -v ./...
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Start RabbitMQ server
        uses: getong/rabbitmq-action@v1.2
        with:
          rabbitmq version: '3.8.2-management-alpine'
          host port: 45672
          rabbitmq user: 'guest'
          rabbitmq password: 'guest'
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          GO111MODULE: on
          CC_TEST_REPORTER_ID: 7d839e0bef19ceb83a38550bc5e651070cd1c15279069a90bdbaaad727d7c0cd
        with:
          coverageCommand: go test -coverprofile c.out ./...
